# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: db
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
